[package]
name = "video_converter_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
lib-core = { path = "../../libs/lib-core" }
no_deadlocks = "1.3.2"
rayon = "1.10"
serde_json = "1"
serde = "1"
